---
title: "Friday"
author: "Eve Fiskebeck"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing data saved as rds (r file format)

object_name <- readRDS("path/to/file_name.rds")

```{r}
library(tidyverse)
library(here)
```


```{r}
here::here()
?filter()
?stats::filter()
?dplyr::filter()
```

```{r}
here::here("data","human_data_selection_dedup.rds")
human_selection <- readRDS(here::here("data","human_data_selection_dedup.rds")
                           ) 
```

# connection to the database in WHONET 

```{r}
#install.packages("RSQLite")
library(RSQLite)
```

```{r}
sqlite_path <- "C:/WHONET/Data/TZA-INIKA_TZ-2024.sqlite"
sqlite_path
dbconn <- DBI::dbConnect(
  RSQLite::SQLite(), 
  sqlite_path
  )

```


```{r}
dbconn
```





```{r}
dbListTables(dbconn)
```

```{r}
mydata_recipie <- tbl(dbconn, "Isolates")
str(mydata_recipie)
head(mydata_recipie)
```

```{r}
show_query(mydata_recipie)
```

```{r}
mydata <- mydata_recipie %>% collect()
```



```{r}
mydata %>% head() %>% print(width = Inf)
human_selection %>% head() %>% print(width = Inf)
```

```{r}
#my_innerjoin <- 
  human_selection %>% 
  # selecting few columns for testing
  #  this can be used to do a short selection of the columns if not all are required
  dplyr::inner_join(mydata, by = c("INIKA_OH_TZ_ID" = "PATIENT_ID")) %>%
  head() %>%
  View()

```

Would it work ? 
```{r}
mydata %>%
  dplyr::inner_join(
    human_selection %>% select(1:3),
    by = c("PATIENT_ID" = "INIKA_OH_TZ_ID")
    ) %>%
    head() %>% 
  View()
```


